apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from apps.home import blueprint
from flask import render_template, request, redirect, url_for
from flask_login import login_required, current_user
from jinja2 import TemplateNotFound
from apps.authentication.models import Users, Task
from sqlalchemy import func
from apps import db
import datetime
import requests

task_hierarchy = []

@blueprint.route('/index')
@login_required
def index():

    user = Users.find_by_username(current_user.username)

    tasks = Task.query.filter_by(user=user).all()
    task_hierarchy = create_hierarchy(tasks)

    return render_template('home/index.html', segment='index', task_hierarchy=task_hierarchy)

def create_task_hierarchy(task):
    print("do nothing")


@blueprint.route('/<template>')
def route_template(template):

    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500


# Helper - Extract current page name from request
def get_segment(request):

    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment

    except:
        return None



@blueprint.route('/add', methods=['POST'])
def add():

    user = Users.find_by_username(current_user.username)

    task_title = request.form.get('task_title')
    task_description = request.form.get('task_description')

    task_due_date_time = request.form.get('due_date_time')
    date_processing = task_due_date_time.replace('T', '-').replace(':', '-').split('-')
    date_processing = [int(v) for v in date_processing]
    task_due_date_time = datetime.datetime(*date_processing)

    parent_task = request.form.get('parent_task')
    
    new_task = Task(title=task_title, description=task_description, due_date=task_due_date_time, user=user, parent_item_id=parent_task)
    db.session.add(new_task)
    db.session.commit()

    update_task_progress_percent(parent_task)

    return redirect(url_for('home_blueprint.index'))


@login_required
@blueprint.route('/delete/<int:task_id>')
def delete(task_id):

    user = Users.find_by_username(current_user.username)

    task = Task.query.filter_by(id=task_id, user=user).first()
    parent_task_id = task.parent_item_id

    delete_task_and_subtasks(task_id)

    update_task_progress_percent(parent_task_id)


    return redirect(url_for('home_blueprint.index'))

def delete_task_and_subtasks(task_id):
    # Get the task and its subtasks
    task = Task.query.get(task_id)
    subtasks = Task.query.filter(Task.parent_item_id == task_id).all()

    # Delete subtasks first
    for subtask in subtasks:
        delete_task_and_subtasks(subtask.id)

    # Delete the current task
    db.session.delete(task)
    db.session.commit()


@login_required
@blueprint.route('/edit', methods=['POST'])
def edit_item():
  
    field = request.form.get("field")
    value = request.form.get("value")
    task_id = request.form.get("id")
    
    task = Task.query.filter_by(id=task_id).first()

    if (field == "title"):
        task.title = value

    elif (field == "description"):
        task.description = value

    elif (field == "due_date"):
        task.due_date = value

    elif (field == "progress"):
        task.progress = value

        task.progress_percent = 0.00 if value == "Not Started" else 100.00

        db.session.commit()

        print("task #" + str(task.id) +  "progress: " + str(task.progress) + str(task.progress_percent) + "%")

        # dictionary mapping task ID to new percent completed
        res = {}

        # update progress_percent of parent task
        if task.parent_item_id:
            update_task_progress_percent(id=task.parent_item_id, id_to_progress_percent=res)

        return res
        
    db.session.commit()

    return None

def update_task_progress_percent(id, id_to_progress_percent = {}):
    
    task_id = id
    task = Task.query.filter_by(id=task_id).first()

    total_child_task_completion = db.session.query(func.sum(Task.progress_percent)).filter(Task.parent_item_id==task.id).scalar()
    num_child_tasks = db.session.query(func.count()).filter(Task.parent_item_id==task.id).scalar()
    percent_complete = total_child_task_completion / num_child_tasks
    
    task.progress_percent = percent_complete

    id_to_progress_percent[task_id] = percent_complete

    if percent_complete == 100:
        task.progress = "Completed"
    elif percent_complete == 0:
        task.progress = "Not Started"

    db.session.commit()

    # update progress_percent of parent task
    if task.parent_item_id:
        update_task_progress_percent(id=task.parent_item_id, id_to_progress_percent=id_to_progress_percent) 






def create_hierarchy(tasks):
    # Map parents to children
    parent_to_children = {}

    for task in tasks:
        task_id, parent_id = task.id, task.parent_item_id

        if parent_id not in parent_to_children:
            parent_to_children[parent_id] = []
        
        parent_to_children[parent_id].append({'task': task, 'children': []})

    # Construct the hierarchy
    root_nodes = parent_to_children[None] # root nodes have a parent of None
    task_hierarchy.clear()

    for root_node in root_nodes:
        build_hierarchy(root_node, parent_to_children)
        task_hierarchy.append(root_node)

    return task_hierarchy

def build_hierarchy(node, parent_to_children):
    task_id = node['task'].id
    node['children'] = parent_to_children.get(task_id)

    if node['children'] != None:
        for child_task in node['children']:
            build_hierarchy(child_task, parent_to_children)

apps/templates/home/auth-reset-password.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Reset Password {% endblock %}

{% block content %}

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-mail auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Reset Password</h3>
                    <div class="input-group mb-3">
                        <input type="email" class="form-control" placeholder="Email">
                    </div>
                    <button class="btn btn-primary mb-4 shadow-2">Reset Password</button>
                    <p class="mb-0 text-muted">Don’t have an account? <a href="/auth-signup.html">Signup</a></p>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/bc_breadcrumb-pagination.html
{% extends "layouts/base.html" %}

{% block title %} UI Breadcrumb {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->
                    <div class="page-header">
                        <div class="page-block">
                            <div class="row align-items-center">
                                <div class="col-md-12">
                                    <div class="page-header-title">
                                        <h5 class="m-b-10">Breadcrumbs & Pagination</h5>
                                    </div>
                                    <ul class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                                        <li class="breadcrumb-item"><a href="javascript:">Basic Componants</a></li>
                                        <li class="breadcrumb-item"><a href="javascript:">Breadcrumbs & Pagination</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                            <div class="row">
                                <!-- [ Breadcrumbs & Pagination ] start -->
                                <div class="col-sm-6">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Breadcrumb</h5>
                                        </div>
                                        <div class="card-body">
                                            <nav aria-label="breadcrumb">
                                                <ol class="breadcrumb">
                                                    <li class="breadcrumb-item active" aria-current="page">Home</li>
                                                </ol>
                                            </nav>
                                            <nav aria-label="breadcrumb">
                                                <ol class="breadcrumb">
                                                    <li class="breadcrumb-item"><a href="#!">Home</a></li>
                                                    <li class="breadcrumb-item active" aria-current="page">Library</li>
                                                </ol>
                                            </nav>
                                            <nav aria-label="breadcrumb">
                                                <ol class="breadcrumb">
                                                    <li class="breadcrumb-item"><a href="#!">Home</a></li>
                                                    <li class="breadcrumb-item"><a href="#!">Library</a></li>
                                                    <li class="breadcrumb-item active" aria-current="page">Data</li>
                                                </ol>
                                            </nav>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Breadcrumb Icon</h5>
                                        </div>
                                        <div class="card-body">
                                            <nav aria-label="breadcrumb">
                                                <ol class="breadcrumb">
                                                    <li class="breadcrumb-item active" aria-current="page"><i class="feather icon-home"></i></li>
                                                </ol>
                                            </nav>
                                            <nav aria-label="breadcrumb">
                                                <ol class="breadcrumb">
                                                    <li class="breadcrumb-item"><a href="#!"><i class="feather icon-home"></i></a></li>
                                                    <li class="breadcrumb-item active" aria-current="page">Library</li>
                                                </ol>
                                            </nav>
                                            <nav aria-label="breadcrumb">
                                                <ol class="breadcrumb">
                                                    <li class="breadcrumb-item"><a href="#!"><i class="feather icon-home"></i></a></li>
                                                    <li class="breadcrumb-item"><a href="#!">Library</a></li>
                                                    <li class="breadcrumb-item active" aria-current="page">Data</li>
                                                </ol>
                                            </nav>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Pagination</h5>
                                        </div>
                                        <div class="card-body">
                                            <nav aria-label="Page navigation example">
                                                <ul class="pagination">
                                                    <li class="page-item"><a class="page-link" href="#!">Previous</a></li>
                                                    <li class="page-item"><a class="page-link" href="#!">1</a></li>
                                                    <li class="page-item"><a class="page-link" href="#!">2</a></li>
                                                    <li class="page-item"><a class="page-link" href="#!">3</a></li>
                                                    <li class="page-item"><a class="page-link" href="#!">Next</a></li>
                                                </ul>
                                            </nav>
                                            <h5 class="mt-5">Working With Icons</h5>
                                            <hr>
                                            <nav aria-label="Page navigation example">
                                                <ul class="pagination">
                                                    <li class="page-item"><a class="page-link" href="#!" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
                                                    <li class="page-item"><a class="page-link" href="#!">1</a></li>
                                                    <li class="page-item"><a class="page-link" href="#!">2</a></li>
                                                    <li class="page-item"><a class="page-link" href="#!">3</a></li>
                                                    <li class="page-item"><a class="page-link" href="#!" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
                                                </ul>
                                            </nav>
                                            <h5 class="mt-5">Disabled and Active States</h5>
                                            <hr>
                                            <nav aria-label="...">
                                                <ul class="pagination">
                                                    <li class="page-item disabled"><span class="page-link">Previous</span></li>
                                                    <li class="page-item"><a class="page-link" href="#!">1</a></li>
                                                    <li class="page-item active"><span class="page-link">2<span class="sr-only">(current)</span></span>
                                                    </li>
                                                    <li class="page-item"><a class="page-link" href="#!">3</a></li>
                                                    <li class="page-item"><a class="page-link" href="#!">Next</a></li>
                                                </ul>
                                            </nav>
                                        </div>
                                    </div>
                                </div>
                                <!-- [ Breadcrumbs & Pagination ] end -->
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->
    
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/index.html
{% extends "layouts/base.html" %}

{% block title %} Todo List {% endblock title %}

{% block stylesheets %}

{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">

            <div class="pcoded-content">
                <div class="pcoded-inner-content">

                    <h1>Todo List of {{ current_user.username }}</h1>

                    {% for root_task in task_hierarchy %}
                        {% with node=root_task %}
                            {% with hierarchy_depth=0 %}
                                {% include 'includes/node.html' %}
                            {% endwith %}
                        {% endwith %}
                        <br><br>
                    {% endfor %}


                    <form action="{{ url_for('home_blueprint.add') }}" method="post">
                        <label for="task">New Task</label> <br>
                        <input type="text" id="task_title" name="task_title" required> </input> <br>
                        <label for="task">Description</label> <br>
                        <input type="text" id="task_description" name="task_description" required> </input> <br>
                        <label for="task">Due</label> <br>
                        <input type="datetime-local" id="due_date_time" name="due_date_time" required> </input> <br>
                        <button type="submit">Add</button>
                    </form>

                    <a href="{{ url_for('authentication_blueprint.logout')}}">Sign Out</a>

                </div>
            </div>

        </div>
    </div>
    <!-- [ Main Content ] end -->       
{% endblock content %}

{% block javascripts %}

    <script type='text/javascript'>
        $(document).ready(function(){
            // Save data
            $(".task_edit").focusout(function(){
                console.log("Focus out");
                // Get task item info
                var id = this.id;
                var split_id = id.split("_");
                var task_id = split_id[2];
                var field_name = split_id[1];
                var new_field_value = this.innerText;

                $.ajax({
                    url: '/edit',
                    type: 'POST',
                    data: { field:field_name, value:new_field_value, id:task_id },
                    success:function(response){
                    if(response == 1){ 
                        console.log('Save successfully'); 
                    }else{ 
                        console.log("Not saved.");  
                    }
                    }
                });
            
            });

            // Update progress status of task
            $(".progress_select").change(function(){
                // Get task item info
                var id = this.id;
                var split_id = id.split("_");
                var task_id = split_id[2];
                var field_name = split_id[1];
                var new_field_value = this.value;

                $.ajax({
                    url: '/edit',
                    type: 'POST',
                    data: { field:field_name, value:new_field_value, id:task_id },
                    success:function(response){

                        task_id_to_progress_percent = response;

                        for (const task_id in task_id_to_progress_percent) {                            
                            $("#task_progress_percent_" + task_id).text(task_id_to_progress_percent[task_id] + "%");
                        }
                    }
                });
            
            });
            
        });
    </script>

{% endblock javascripts %}

apps/templates/home/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-unlock auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Login</h3>
                    <div class="input-group mb-3">
                        <input type="email" class="form-control" placeholder="Email">
                    </div>
                    <div class="input-group mb-4">
                        <input type="password" class="form-control" placeholder="password">
                    </div>
                    <div class="form-group text-left">
                        <div class="checkbox checkbox-fill d-inline">
                            <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-a1" checked="">
                            <label for="checkbox-fill-a1" class="cr"> Save Details</label>
                        </div>
                    </div>
                    <button class="btn btn-primary shadow-2 mb-4">Login</button>
                    <p class="mb-2 text-muted">Forgot password? <a href="/auth-reset-password.html">Reset</a></p>
                    <p class="mb-0 text-muted">Don’t have an account? <a href="/register.html">Sign UP</a></p>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} 404 Page {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather x-circle"></i>
                    </div>
                    <h3 class="mb-4">Error 404</h3>

                    <br />

                    <span class="mb-0 text-muted">
                        Page not found - <a href="/">Home</a> 
                    </span>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

apps/templates/home/page-500.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} 500 Page {% endblock %}

{% block content %}   

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather x-circle"></i>
                    </div>
                    <h3 class="mb-4">Error 500</h3>

                    <br />

                    <span class="mb-0 text-muted">
                        Server Error - <a href="/">Home</a> 
                    </span>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

apps/templates/home/page-blank.html
{% extends "layouts/base.html" %}

{% block title %} Page Blank {% endblock %} 

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-wrapper">
            <div class="pcoded-content">
                <div class="pcoded-inner-content">
                    <!-- [ breadcrumb ] start -->
                    <div class="page-header">
                        <div class="page-block">
                            <div class="row align-items-center">
                                <div class="col-md-12">
                                    <div class="page-header-title">
                                        <h5 class="m-b-10">Sample Page</h5>
                                    </div>
                                    <ul class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                                        <li class="breadcrumb-item"><a href="javascript:">Sample Page</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ breadcrumb ] end -->
                    <div class="main-body">
                        <div class="page-wrapper">
                            <!-- [ Main Content ] start -->
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Hello card</h5>
                                        </div>
                                        <div class="card-block">
                                            <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- [ Main Content ] end -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Register {% endblock %}

{% block content %}

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather icon-user-plus auth-icon"></i>
                    </div>
                    <h3 class="mb-4">Sign up</h3>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Username">
                    </div>
                    <div class="input-group mb-3">
                        <input type="email" class="form-control" placeholder="Email">
                    </div>
                    <div class="input-group mb-4">
                        <input type="password" class="form-control" placeholder="password">
                    </div>
                    <div class="form-group text-left">
                        <div class="checkbox checkbox-fill d-inline">
                            <input type="checkbox" name="checkbox-fill-1" id="checkbox-fill-1" checked="">
                            <label for="checkbox-fill-1" class="cr"> Save Details</label>
                        </div>
                    </div>
                    <div class="form-group text-left">
                        <div class="checkbox checkbox-fill d-inline">
                            <input type="checkbox" name="checkbox-fill-2" id="checkbox-fill-2">
                            <label for="checkbox-fill-2" class="cr">Send me the <a href="#!"> Newsletter</a> weekly.</label>
                        </div>
                    </div>
                    <button class="btn btn-primary shadow-2 mb-4">Sign up</button>
                    <p class="mb-0 text-muted">Allready have an account? <a href="/login.html"> Sign IN</a></p>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}